version: '3'

services:
  SCMXPERT:
    image: yaswanth2001/scmxpertlite:latest
    ports:
      - '8001:8001'


  zookeeper:
    image: 'ubuntu/zookeeper:latest'
    ports:
      - '2181:2181'
    depends_on:
     - SCMXPERT
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes


  kafka:
    image: ubuntu/kafka:latest
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_HEAP_OPTS=-Xmx1G


  server:
    image: yaswanth2001/scmserver:latest
    ports:
      - '9999:9999'
    depends_on:
      - kafka
  

  producer:
    image: yaswanth2001/scmproducer:latest
    depends_on:
      - server
    environment:
      - port=9999
      - host=server
      - bootstrap-servers=kafka:9092
      - topic=Device


  consumer:
    image: yaswanth2001/scmconsumer:latest
    depends_on:
      - producer
    environment:
      - bootstrap-servers=kafka:9092
      - topic=Device
      - MONGODB_URL=mongodb+srv://yaswanthg9966:iqUGvzM42gzFrIwH@cluster0.tzvgwaf.mongodb.net/
      - group_id=scm-consumer
      - data_base_name=SCMXPERTLITE
      - collection=DEVICE_DATA
  